version: '3'

services:

  database-mysql:
    image: mysql:5.6
    hostname: mysql
    container_name: mysql
    ports:
      - 3307:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/var/lib/mysql

    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: useraccess
      MYSQL_USER: useraccess
      MYSQL_PASSWORD: 1234

    network_mode: bridge

  user-access:
    build:
      context: .
      dockerfile: Dockerfile
    image: com.eltonsandre/user-access:latest
    hostname: user-access
    container_name: user-access
    ports:
      - 8084:80
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - database-mysql
    network_mode: bridge
    links:
      - database-mysql
